# Generated by Django 4.0.3 on 2022-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('将棋', '将棋'), ('日常のこと', '日常のこと'), ('プログラミングについて', 'プログラミングについて')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
